name: ann-qq-bot
channels:
  - defaults
dependencies:
  - python=3.10.4
  - pip
  - requests=2.27.1
  - pyyaml=6.0
  - lxml=4.8.0
  - pip:
    - graia-ariadne==0.6.16
    - oss2
    - aliyun-python-sdk-core==2.13.3
    - matplotlib==3.3.4
